- name: Install and config Nginx
  include_role:
    role: geerlingguy.htpasswd
  vars:
    htpasswd_credentials:
      - path: /etc/nginx/htpasswd-admins
        name: cypress
        password: 'XXXXXXXXXX'
        owner: root
        group: www-data
        mode: 'u+rw,g+r'
