- name: letsencrypt
  become: yes
  include: ssl.yml
  tags:
    - nginx
    - ssl
- name: Htpasswd
  become: yes
  include: htpasswd.yml
  tags:
    - nginx
    - htpasswd
- name: Nginx
  become: yes
  include: nginx.yml
  tags:
    - nginx
