- name: letsencrypt
  sudo : yes
  include: ssl.yml
  tags:
    - nginx
    - ssl
- name: Htpasswd
  sudo : yes
  include: htpasswd.yml
  tags:
    - nginx
    - htpasswd
- name: Nginx
  sudo : yes
  include: nginx.yml
  tags:
    - nginx
