- name: Nginx var config debug
  debug:
      msg:
      - "server_name: {{ ansible_fqdn }}"
      - "ssl_certificate /etc/letsencrypt/live/{{ ansible_fqdn }}/fullchain.pem;"
      - "ssl_certificate_key /etc/letsencrypt/live/{{ ansible_fqdn }}/privkey.pem;"
- name: Install and config Nginx
  include_role:
    role: geerlingguy.nginx
  vars:
    nginx_vhosts:
      - listen: "80"
        filename: "redirect_to_ssl.conf"
        server_name: "{{ ansible_fqdn }}"
        extra_parameters: |
          return  301 https://$server_name$request_uri;
      - listen: "443 ssl http2"
        filename: "locked_kibana.conf"
        server_name: "{{ ansible_fqdn }}"
        state: "present"
        error_log: "/var/log/nginx/locked-kibana.error.log"
        access_log: "/var/log/nginx/locked-kibana.access.log"
        extra_parameters: |
          ssl_certificate /etc/letsencrypt/live/{{ ansible_fqdn }}/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/{{ ansible_fqdn }}/privkey.pem;
          ssl_protocols TLSv1.2;
          ssl_prefer_server_ciphers on;
          ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK';
          ssl_dhparam /etc/nginx/dhparams.pem;
          add_header Strict-Transport-Security max-age=63072000;


          ssl_session_cache shared:SSL:10m;
          ssl_session_timeout 10m;

          # Read only access to Kibana
          # deny other than get/post/options/head
          # allow post when used with _search/_msearch/_mget
          # allow get/options/head
          set $posting 11;
          if ( $request_method !~ ^(GET|POST|OPTIONS|HEAD)$ )                     { return 405; }
          if ( $request_method = POST )                                           { set $posting 1; }
          if ( $request_uri ~ ^/(.+)/(_search|_mget|_msearch|_field_stats|_bulk_get)(.*)$ ) { set $posting "${posting}1"; }
          if ( $request_method ~ ^(GET|OPTIONS|HEAD)$ )                           { set $posting 11; }
          if ( $posting != 11 )                                                   { return 403; }

          location / {
            proxy_pass http://127.0.0.1:5601;
            proxy_redirect off;
            add_header Access-Control-Allow-Origin *;
            proxy_set_header X-Real-IP  $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_set_header Connection "Keep-Alive";
            proxy_set_header Proxy-Connection "Keep-Alive";
          }
      - listen: "8443 ssl http2"
        filename: "admin_kibana.conf"
        server_name: "{{ ansible_fqdn }}"
        state: "present"
        error_log: "/var/log/nginx/admin-kibana.error.log"
        access_log: "/var/log/nginx/admin-kibana.access.log"
        extra_parameters: |
          ssl_certificate /etc/letsencrypt/live/{{ ansible_fqdn }}/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/{{ ansible_fqdn }}/privkey.pem;
          ssl_protocols TLSv1.2;
          ssl_prefer_server_ciphers on;
          ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK';
          ssl_dhparam /etc/nginx/dhparams.pem;
          add_header Strict-Transport-Security max-age=63072000;


          ssl_session_cache shared:SSL:10m;
          ssl_session_timeout 10m;

          location / {
              auth_basic "Kibana Admins";
              auth_basic_user_file /etc/nginx/htpasswd-admins;

              proxy_redirect off;

              proxy_set_header X-Real-IP  $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header Host $http_host;
              proxy_set_header Connection "Keep-Alive";
              proxy_set_header Proxy-Connection "Keep-Alive";

              proxy_pass http://127.0.0.1:5601;
            }
      - listen: "9200 ssl http2"
        filename: "admin_elasticsearch.conf"
        server_name: "{{ ansible_fqdn }}"
        state: "present"
        error_log: "/var/log/nginx/admin-elasticsearch.error.log"
        access_log: "/var/log/nginx/admin-elasticsearch.access.log"
        extra_parameters: |
          ssl_certificate /etc/letsencrypt/live/{{ ansible_fqdn }}/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/{{ ansible_fqdn }}/privkey.pem;
          ssl_protocols TLSv1.2;
          ssl_prefer_server_ciphers on;
          ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK';
          ssl_dhparam /etc/nginx/dhparams.pem;
          add_header Strict-Transport-Security max-age=63072000;


          ssl_session_cache shared:SSL:10m;
          ssl_session_timeout 10m;

          location / {
              auth_basic "Elastcsearch Admins";
              auth_basic_user_file /etc/nginx/htpasswd-admins;

              proxy_redirect off;

              proxy_set_header X-Real-IP  $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header Host $http_host;
              proxy_set_header Connection "Keep-Alive";
              proxy_set_header Proxy-Connection "Keep-Alive";

              proxy_pass http://127.0.0.1:9201;
            }
