- firewalld:
    service: http
    permanent: yes
    state: enabled
- firewalld:
    service: https
    permanent: yes
    state: enabled
- firewalld:
    port: 8443/tcp
    permanent: yes
    state: enabled
- firewalld:
    port: 9200/tcp
    permanent: yes
    state: enabled
- firewalld:
    port: 9203/tcp
    permanent: yes
    state: enabled
- firewalld:
    port: "{{ansible_port}}/tcp"
    permanent: yes
    state: enabled
